def resourceProperties = [version: project.version.toString()]

sourceSets {
    main {
        resources {
            srcDir '../common/src/main/resources'
        }
    }
}

dependencies {
    implementation project(':common')
    implementation project(':bootstrap')

    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'
    compileOnly 'org.bstats:bstats-bukkit:3.2.1'
    compileOnly 'com.zaxxer:HikariCP:7.0.2'
    compileOnly 'org.mindrot:jbcrypt:0.4'
    compileOnly 'dev.samstevens.totp:totp:1.7.1'
    compileOnly 'com.mysql:mysql-connector-j:9.6.0'
}

tasks.processResources {
    inputs.properties(resourceProperties)
    filesMatching('plugin.yml') {
        expand(resourceProperties)
    }
}

tasks.jar {
    enabled = false
}
